version: '3'
services:
  fc-monolito:
    build:
      context: .
      dockerfile: Dockerfile
    image: fc-monolito
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm test